# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Hype Forever: Dev Blog"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Development blog of Hype Forever. We plan on posting regular updates
  about the development progress & things we consider interesting. The blog is
  currently in an early state, you really shouldn't be here yet :)
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://hypeforever.github.io" # the base hostname & protocol for your site

# Social media
facebook_group_name: hypeforever
facebook_group_id: 126929554163825

github_username: hypeforever

# Build settings
markdown: kramdown
